apiVersion: resource.nvidia.com/v1beta1
kind: ComputeDomain
metadata:
  name: compute-domain-job0
  namespace: standard
spec:
  numNodes: 0 # no longer needed
  channel:
    resourceClaimTemplate:
      name: compute-domain-job0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job0
  namespace: standard
spec:
  completions: 4
  parallelism: 4
  completionMode: Indexed
  template:
    spec:
      schedulerName: dra-scheduler
      containers:
      - name: worker
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["date; sleep 300; date"]
        resources:
          claims:
          - name: gpus
          - name: compute-domain
      restartPolicy: Never
      resourceClaims:
      - name: gpus
        resourceClaimTemplateName: all-gpus
      - name: compute-domain
        resourceClaimTemplateName: compute-domain-job0
