//go:build !ignore_autogenerated

/*
 * Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package resource

import (
	"github.com/kubernetes-sigs/wg-device-management/nv-partitionable-resources/pkg/intrange"
	"k8s.io/api/resource/v1alpha2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesInstance) DeepCopyInto(out *NamedResourcesInstance) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]v1alpha2.NamedResourcesAttribute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]NamedResourcesSharedResourceGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesInstance.
func (in *NamedResourcesInstance) DeepCopy() *NamedResourcesInstance {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesResources) DeepCopyInto(out *NamedResourcesResources) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]NamedResourcesInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SharedLimits != nil {
		in, out := &in.SharedLimits, &out.SharedLimits
		*out = make([]NamedResourcesSharedResourceGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesResources.
func (in *NamedResourcesResources) DeepCopy() *NamedResourcesResources {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesSharedResource) DeepCopyInto(out *NamedResourcesSharedResource) {
	*out = *in
	in.NamedResourcesSharedResourceValue.DeepCopyInto(&out.NamedResourcesSharedResourceValue)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesSharedResource.
func (in *NamedResourcesSharedResource) DeepCopy() *NamedResourcesSharedResource {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesSharedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesSharedResourceGroup) DeepCopyInto(out *NamedResourcesSharedResourceGroup) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamedResourcesSharedResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesSharedResourceGroup.
func (in *NamedResourcesSharedResourceGroup) DeepCopy() *NamedResourcesSharedResourceGroup {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesSharedResourceGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesSharedResourceValue) DeepCopyInto(out *NamedResourcesSharedResourceValue) {
	*out = *in
	if in.QuantityValue != nil {
		in, out := &in.QuantityValue, &out.QuantityValue
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.IntRangeValue != nil {
		in, out := &in.IntRangeValue, &out.IntRangeValue
		*out = new(intrange.IntRange)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesSharedResourceValue.
func (in *NamedResourcesSharedResourceValue) DeepCopy() *NamedResourcesSharedResourceValue {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesSharedResourceValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceModel) DeepCopyInto(out *ResourceModel) {
	*out = *in
	if in.NamedResources != nil {
		in, out := &in.NamedResources, &out.NamedResources
		*out = new(NamedResourcesResources)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceModel.
func (in *ResourceModel) DeepCopy() *ResourceModel {
	if in == nil {
		return nil
	}
	out := new(ResourceModel)
	in.DeepCopyInto(out)
	return out
}
